import PaginaPrincipal from './PaginaPrincipal/page'
import Navbar from './components/Navbar'
import "../../styles/globals.css"
import { Inter } from 'next/font/google'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ITbank',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>{children}
      </body>
    </html>
  )
}
